### PR TITLE
Remove @ember-decorators/babel-transforms

### PR DESCRIPTION
**Pull request by CvX**
On recent `ember-cli` versions, `ember-functional-modifiers` has been triggering the following warning:

> [APP NAME] has added the class-properties plugin to its build, but ember-cli-babel provides these by default now! You can remove the transforms, or the addon that provided them, such as @ember-decorators/babel-transforms.

This PR removes `@ember-decorators/babel-transforms` dependency, as it doesn't seem needed anymore.

~~It also updates an old-style Ember import that was making ESLint fail.~~
~~(looks like something was wrong in either node_modules or an incompatibility with globally installed npm packages; I've removed that commit)~~

btw. if tests on ember 2.x are marked as allowed to fail, and they do fail, should they be run at all?

### CODE REVIEW

**Comment by CvX** [comment]
Hmm… I get totally different results locally and on travis… 👀

```
------ RESULTS ------

Scenario ember-lts-2.18: FAIL
Command run: ember test
with env: {
  "EMBER_OPTIONAL_FEATURES": "{\"jquery-integration\":true}"
}
Scenario ember-lts-3.4: SUCCESS
Command run: ember test
Scenario ember-release: SUCCESS
Command run: ember test
Scenario ember-beta: SUCCESS
Command run: ember test
Scenario ember-canary: SUCCESS
Command run: ember test
Scenario ember-default: SUCCESS
Command run: ember test
Scenario ember-default-with-jquery: SUCCESS
Command run: ember test
with env: {
  "EMBER_OPTIONAL_FEATURES": "{\"jquery-integration\":true}"
}

1 scenarios failed
6 scenarios succeeded
7 scenarios run
```

**Comment by spencer516** [comment]
Hi! Thanks for doing this. 

Regarding the failures: weird — it looks to me like the test failure is a linting failure unrelated to your changes. 🤔 

(I wonder if travis is ending up with a newer version of `eslint-plugin-ember` or something that has a new rule in it?)

```
message: >
            addon/index.js should pass ESLint
            
            24:10 - Use import { setModifierManager } from '@ember/modifier'; instead of using Ember._setModifierManager (ember/new-module-imports)
```

Do you want to try doing as it says and update that import statement and see if this passes? 

And, the other questions: 

> On travis "Additional test" run yarn node-test in addition to yarn try but the same isn't done for stage "Tests". Is this intentional?

I think I just used the standard off-the-shelf travis file when you create a new addon. So, it may be intentional, but I'm not sure the reasoning.


> package.json specifies supported engines to include 6.x and 8.x but travis runs the tests only on 10.x. Again, is this intentional?

Definitely not intentional — would happily merge a PR to address that (or, if you want to open an issue I can get to it when I get a chance!)

**Comment by spencer516** [comment]
I also just saw your crossed out comment about that eslint failure: 

> It also updates an old-style Ember import that was making ESLint fail.

hmmmm....is something else going on?

**Comment by CvX** [comment]
Here's the failed build with new style import: https://travis-ci.com/spencer516/ember-functional-modifiers/builds/108564828 It fails with:

> Error: Could not find module `@ember/modifier` imported from `ember-functional-modifiers/index`

So the build fails in either case. (though sometimes passes, but only locally?)

Maybe updating dependencies would make this issue go away… There's quite a lot of stuff that could be bumped:

yarn outdated

Let's see…

```sh
> rm -rf node_modules && yarn && yarn test
(…) Use import { setModifierManager } from '@ember/modifier'; instead of using Ember._setModifierManager (ember/new-module-imports)
(…) Tests failed.

> git checkout fc9e642c && yarn test # new style import
(…) Could not find module `@ember/modifier` imported from `ember-functional-modifiers/index`
(…) Tests failed.

> git checkout class-properties && yarn upgrade --latest && yarn test
(…) Use import { setModifierManager } from '@ember/modifier'; instead of using Ember._setModifierManager (ember/new-module-imports)
(…) Tests failed.

> git checkout fc9e642c && yarn test # new style import
(…) # ok
😯

> yarn test:all
(…) 1 scenarios failed # ember-lts-2.18
6 scenarios succeeded
🎉
```

So… maybe that's the way. 😉

**Comment by spencer516** [comment]
Awesome! Will merge and publish a new version shortly.

**Pull request merged**
